# Generated by Django 6.0.1 on 2026-02-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('unauthorized', 'Неавторизированный'), ('authorized', 'Авторизированный'), ('editor', 'Редактор'), ('admin', 'Администратор')], default='authorized', max_length=20, verbose_name='Роль'),
        ),
    ]
